services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: voca-app-dev
    restart: unless-stopped
    ports:
      - "7024:7024"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@voca-postgres:5432/${POSTGRES_DB}?schema=public
      NODE_ENV: development
    networks:
      - voca-network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: sh start-dev.sh

networks:
  voca-network:
    external: true
    name: voca-web_voca-network